language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: npm install && npm run build
      deploy:
        provider: npm
        email: anissoftkun@gmail.com
        api_key: $NPMJS_ACCESS_TOKEN
        script:
          - "npm run build"
          - "cp .template.npmrc $HOME/.npmrc"
          - "npm publish"
        skip_cleanup: true
        on:
          branch: master
notifications:
  email:
    recipients:
      - anissoftkun@gmail.com
    on_success: change
    on_failure: always
