language: node_js
node_js:
  - "10"

deploy:
  edge: true
  provider: script
  email: anissoftkun@gmail.com
  api_key: $NPMJS_ACCESS_TOKEN
  script: "npm install && npm run build && cp .template.npmrc $HOME/.npmrc && cat $HOME/.npmrc && npm"
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    recipients:
      - anissoftkun@gmail.com
    on_success: change
    on_failure: always
